/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWanRouteImport } from './routes/_authenticated.wan'
import { Route as AuthenticatedTopologyRouteImport } from './routes/_authenticated.topology'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRawRouteImport } from './routes/_authenticated.raw'
import { Route as AuthenticatedPortsRouteImport } from './routes/_authenticated.ports'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated.network'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated.logs'
import { Route as AuthenticatedInternalRouteImport } from './routes/_authenticated.internal'
import { Route as AuthenticatedFirewallRouteImport } from './routes/_authenticated.firewall'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated.events'
import { Route as AuthenticatedDpiRouteImport } from './routes/_authenticated.dpi'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated.clients'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWanRoute = AuthenticatedWanRouteImport.update({
  id: '/wan',
  path: '/wan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTopologyRoute = AuthenticatedTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRawRoute = AuthenticatedRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortsRoute = AuthenticatedPortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInternalRoute = AuthenticatedInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFirewallRoute = AuthenticatedFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDpiRoute = AuthenticatedDpiRouteImport.update({
  id: '/dpi',
  path: '/dpi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dpi': typeof AuthenticatedDpiRoute
  '/events': typeof AuthenticatedEventsRoute
  '/firewall': typeof AuthenticatedFirewallRoute
  '/internal': typeof AuthenticatedInternalRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/ports': typeof AuthenticatedPortsRoute
  '/raw': typeof AuthenticatedRawRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/topology': typeof AuthenticatedTopologyRoute
  '/wan': typeof AuthenticatedWanRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dpi': typeof AuthenticatedDpiRoute
  '/events': typeof AuthenticatedEventsRoute
  '/firewall': typeof AuthenticatedFirewallRoute
  '/internal': typeof AuthenticatedInternalRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/ports': typeof AuthenticatedPortsRoute
  '/raw': typeof AuthenticatedRawRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/topology': typeof AuthenticatedTopologyRoute
  '/wan': typeof AuthenticatedWanRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dpi': typeof AuthenticatedDpiRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/firewall': typeof AuthenticatedFirewallRoute
  '/_authenticated/internal': typeof AuthenticatedInternalRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/ports': typeof AuthenticatedPortsRoute
  '/_authenticated/raw': typeof AuthenticatedRawRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/topology': typeof AuthenticatedTopologyRoute
  '/_authenticated/wan': typeof AuthenticatedWanRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/clients'
    | '/dpi'
    | '/events'
    | '/firewall'
    | '/internal'
    | '/logs'
    | '/network'
    | '/ports'
    | '/raw'
    | '/settings'
    | '/topology'
    | '/wan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/clients'
    | '/dpi'
    | '/events'
    | '/firewall'
    | '/internal'
    | '/logs'
    | '/network'
    | '/ports'
    | '/raw'
    | '/settings'
    | '/topology'
    | '/wan'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/_authenticated/clients'
    | '/_authenticated/dpi'
    | '/_authenticated/events'
    | '/_authenticated/firewall'
    | '/_authenticated/internal'
    | '/_authenticated/logs'
    | '/_authenticated/network'
    | '/_authenticated/ports'
    | '/_authenticated/raw'
    | '/_authenticated/settings'
    | '/_authenticated/topology'
    | '/_authenticated/wan'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wan': {
      id: '/_authenticated/wan'
      path: '/wan'
      fullPath: '/wan'
      preLoaderRoute: typeof AuthenticatedWanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topology': {
      id: '/_authenticated/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof AuthenticatedTopologyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raw': {
      id: '/_authenticated/raw'
      path: '/raw'
      fullPath: '/raw'
      preLoaderRoute: typeof AuthenticatedRawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ports': {
      id: '/_authenticated/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof AuthenticatedPortsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/internal': {
      id: '/_authenticated/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof AuthenticatedInternalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/firewall': {
      id: '/_authenticated/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof AuthenticatedFirewallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dpi': {
      id: '/_authenticated/dpi'
      path: '/dpi'
      fullPath: '/dpi'
      preLoaderRoute: typeof AuthenticatedDpiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDpiRoute: typeof AuthenticatedDpiRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFirewallRoute: typeof AuthenticatedFirewallRoute
  AuthenticatedInternalRoute: typeof AuthenticatedInternalRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedPortsRoute: typeof AuthenticatedPortsRoute
  AuthenticatedRawRoute: typeof AuthenticatedRawRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTopologyRoute: typeof AuthenticatedTopologyRoute
  AuthenticatedWanRoute: typeof AuthenticatedWanRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDpiRoute: AuthenticatedDpiRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFirewallRoute: AuthenticatedFirewallRoute,
  AuthenticatedInternalRoute: AuthenticatedInternalRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedPortsRoute: AuthenticatedPortsRoute,
  AuthenticatedRawRoute: AuthenticatedRawRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTopologyRoute: AuthenticatedTopologyRoute,
  AuthenticatedWanRoute: AuthenticatedWanRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
